spring.application.name=portifolio-projetos-api
spring.jpa.hibernate.ddl-auto=none

#conexao db
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_boot_api
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver